import { Component, input, signal } from '@angular/core';                                                                                                                                                      
import { DecimalPipe } from '@angular/common';                                                                                                                                                                 
import { Stock } from '../../stock.service';                                                                                                                                                                   
                                                                                                                                                                                                                
@Component({                                                                                                                                                                                                   
  selector: 'app-detail-panel',                                                                                                                                                                                
  imports: [DecimalPipe],                                                                                                                                                                                      
  templateUrl: './detail-panel.html',                                                                                                                                                                          
  styleUrl: './detail-panel.css',                                                                                                                                                                              
})                                                                                                                                                                                                             
export class DetailPanel {                                                                                                                                                                                     
  stock = input.required<Stock>();                                                                                                                                                                             
  history = input.required<{ date: string; close: number; volume: number }[]>();                                                                                                                               
                                                                                                                                                                                                                
  tradeQuantity = signal<number>(100);                                                                                                                                                                         
  tradeType = signal<'BUY' | 'SELL'>('BUY');                                                                                                                                                                   
  tradeSuccessMessage = signal<string | null>(null);                                                                                                                                                           
                                                                                                                                                                                                                
  setTradeType(type: 'BUY' | 'SELL') {                                                                                                                                                                         
    this.tradeType.set(type);                                                                                                                                                                                  
  }                                                                                                                                                                                                            
                                                                                                                                                                                                                
  onTradeQuantityInput(event: Event) {                                                                                                                                                                         
    const target = event.target as HTMLInputElement;                                                                                                                                                           
    const qty = parseInt(target.value) || 0;                                                                                                                                                                   
    this.tradeQuantity.set(Math.max(1, qty));                                                                                                                                                                  
  }                                                                                                                                                                                                            
                                                                                                                                                                                                                
  executeMockTrade() {                                                                                                                                                                                         
    const qty = this.tradeQuantity();                                                                                                                                                                          
    const total = qty * this.stock().price;                                                                                                                                                                    
    const formattedTotal = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(total);                                                                     
                                                                                                                                                                                                                
    this.tradeSuccessMessage.set(                                                                                                                                                                              
      `Submitted: ${this.tradeType()} ${qty} shares of ${this.stock().symbol} at Rp ${this.stock().price} (Total: ${formattedTotal})!`                                                                         
    );                                                                                                                                                                                                         
                                                                                                                                                                                                                
    setTimeout(() => {                                                                                                                                                                                         
      this.tradeSuccessMessage.set(null);                                                                                                                                                                      
    }, 4000);                                                                                                                                                                                                  
  }                                                                                                                                                                                                            
                                                                                                                                                                                                                
  getHistoryChartPoints(history: { close: number }[]): string {                                                                                                                                                
    if (!history || history.length === 0) return '';                                                                                                                                                           
    const closes = history.map(h => h.close);                                                                                                                                                                  
    const min = Math.min(...closes);                                                                                                                                                                           
    const max = Math.max(...closes);                                                                                                                                                                           
    const range = max - min || 1;                                                                                                                                                                              
    const width = 300;                                                                                                                                                                                         
    const height = 100;                                                                                                                                                                                        
                                                                                                                                                                                                                
    return history.map((item, idx) => {                                                                                                                                                                        
      const x = (idx / (history.length - 1)) * width;                                                                                                                                                          
      const y = height - ((item.close - min) / range) * height;                                                                                                                                                
      return `${x.toFixed(1)},${y.toFixed(1)}`;                                                                                                                                                                
    }).join(' ');                                                                                                                                                                                              
  }                                                                                                                                                                                                            
                                                                                                                                                                                                                
  getStockNews(symbol: string): { title: string; time: string; source: string }[] {                                                                                                                            
    return [                                                                                                                                                                                                   
      { title: `${symbol} Reports Strong Q2 Results, Exceeding Consensus Estimates`, time: '2h ago', source: 'Bloomberg IDX' },                                                                                
      { title: `IDX Sector Analysis: What's Next for ${symbol} and Peers?`, time: '5h ago', source: 'Kontan News' },                                                                                           
      { title: `Analysts Maintain Recommendations for ${symbol} Post Latest Review`, time: '1d ago', source: 'Indo Premier' }                                                                                  
    ];                                                                                                                                                                                                         
  }                                                                                                                                                                                                            
}   