export const TICKERS = [                                                                                                                                                                                       
      'ELSA.JK', 'ARCI.JK', 'PGAS.JK', 'PGEO.JK', 'ADRO.JK', 'TINS.JK', 'INDY.JK', 'SMIL.JK', 'HRTA.JK', 'WIRG.JK',                                                                                                
      'INDF.JK', 'BSDE.JK', 'DSNG.JK', 'BRMS.JK', 'PWON.JK', 'SIDO.JK', 'AKRA.JK', 'TOBA.JK', 'ITMG.JK', 'INCO.JK',                                                                                                
      'ADMR.JK', 'INKP.JK', 'DSSA.JK', 'BBTN.JK', 'AADI.JK', 'WIFI.JK', 'ACES.JK', 'INTP.JK', 'TOWR.JK', 'ANTM.JK',                                                                                                
      'UNTR.JK', 'INET.JK', 'TAPG.JK', 'CTRA.JK', 'PNLF.JK', 'ESSA.JK', 'AMMN.JK', 'PANI.JK', 'PTBA.JK', 'KIJA.JK',                                                                                                
      'JSMR.JK', 'HMSP.JK', 'SMGR.JK', 'HRUM.JK', 'MAPI.JK', 'CPIN.JK', 'BRPT.JK', 'ERAA.JK', 'UNVR.JK', 'BMRI.JK',                                                                                                
      'KLBF.JK', 'PSAB.JK', 'CMRY.JK', 'MIKA.JK', 'MEDC.JK', 'FILM.JK', 'GOTO.JK', 'BRIS.JK', 'SMRA.JK', 'SSIA.JK',                                                                                                
      'DEWA.JK', 'JPFA.JK', 'BUKA.JK', 'BTPS.JK', 'MBMA.JK', 'PTRO.JK', 'HEAL.JK', 'CBDK.JK', 'BUMI.JK', 'BBRI.JK',                                                                                                
      'ICBP.JK', 'MDKA.JK', 'CUAN.JK', 'BBCA.JK', 'EXCL.JK', 'ENRG.JK', 'MYOR.JK', 'EMTK.JK', 'BBNI.JK', 'BULL.JK',                                                                                                
      'KPIG.JK', 'TPIA.JK', 'BKSL.JK', 'MAPA.JK', 'IMPC.JK', 'BUVA.JK', 'AMRT.JK', 'ASII.JK', 'RATU.JK', 'NCKL.JK',                                                                                                
      'SCMA.JK', 'SGER.JK', 'TLKM.JK', 'TCPI.JK', 'RAJA.JK', 'MTEL.JK', 'ISAT.JK', 'BBYB.JK', 'BREN.JK', 'ARTO.JK'                                                                                                 
    ];                                                                                                                                                                                                             
                                                                                                                                                                                                                   
    export const STOCK_DETAILS = {
      'ELSA.JK': { name: 'Elnusa Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'ARCI.JK': { name: 'Archi Indonesia Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'PGAS.JK': { name: 'Perusahaan Gas Negara Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'PGEO.JK': { name: 'Pertamina Geothermal Energy Tbk', sector: 'IDXINFRA', sectorDesc: 'Infrastructure', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'ADRO.JK': { name: 'Adaro Energy Indonesia Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'TINS.JK': { name: 'Timah Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'INDY.JK': { name: 'Indika Energy Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'SMIL.JK': { name: 'Sarana Mitra Luas Tbk', sector: 'IDXTRANS', sectorDesc: 'Transportation & Logistics', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'HRTA.JK': { name: 'Hartadinata Abadi Tbk', sector: 'IDXCYCLIC', sectorDesc: 'Consumer Cyclicals', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'WIRG.JK': { name: 'WIR Asia Tbk', sector: 'IDXTECHNO', sectorDesc: 'Technology', indices: ['KOMPAS100', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'INDF.JK': { name: 'Indofood Sukses Makmur Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'LQ45', 'IDX80', 'ISSI'] },
      'BSDE.JK': { name: 'Bumi Serpong Damai Tbk', sector: 'IDXPROPERT' ,sectorDesc: 'Properties & Real Estate', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'DSNG.JK': { name: 'Dharma Satya Nusantara Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'BRMS.JK': { name: 'Bumi Resources Minerals Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'PWON.JK': { name: 'Pakuwon Jati Tbk', sector: 'IDXPROPERT' ,sectorDesc: 'Properties & Real Estate', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'SIDO.JK': { name: 'Industri Jamu dan Farmasi Sido Muncul Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'AKRA.JK': { name: 'AKR Corporindo Tbk', sector: 'IDXINDUST' ,sectorDesc: 'Industrials', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'TOBA.JK': { name: 'TBS Energi Utama Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'ITMG.JK': { name: 'Indo Tambangraya Megah Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'INCO.JK': { name: 'Vale Indonesia Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'ADMR.JK': { name: 'Adaro Minerals Indonesia Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'INKP.JK': { name: 'Indah Kiat Pulp & Paper Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'DSSA.JK': { name: 'Dian Swastatika Sentosa Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'LQ45', 'IDX80', 'ISSI'] },
      'BBTN.JK': { name: 'Bank Tabungan Negara Tbk', sector: 'IDXFINANCE' ,sectorDesc: 'Financials', indices: ['KOMPAS100', 'LQ45', 'IDX80'] },
      'AADI.JK': { name: 'Adaro Andalan Indonesia Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'WIFI.JK': { name: 'Solusi Sinergi Digital Tbk', sector: 'IDXINFRA', sectorDesc: 'Infrastructure', indices: ['KOMPAS100', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'ACES.JK': { name: 'Aspirasi Hidup Indonesia Tbk', sector: 'IDXCYCLIC', sectorDesc: 'Consumer Cyclicals', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'INTP.JK': { name: 'Indocement Tunggal Prakarsa Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'TOWR.JK': { name: 'Sarana Menara Nusantara Tbk', sector: 'IDXINFRA', sectorDesc: 'Infrastructure', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'ANTM.JK': { name: 'Aneka Tambang Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'UNTR.JK': { name: 'United Tractors Tbk', sector: 'IDXINDUST' ,sectorDesc: 'Industrials', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'INET.JK': { name: 'Sinergi Inti Andalan Prima Tbk', sector: 'IDXTECHNO', sectorDesc: 'Technology', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'TAPG.JK': { name: 'Triputra Agro Persada Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'CTRA.JK': { name: 'Ciputra Development Tbk', sector: 'IDXPROPERT' ,sectorDesc: 'Properties & Real Estate', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'PNLF.JK': { name: 'Panin Financial Tbk', sector: 'IDXFINANCE' ,sectorDesc: 'Financials', indices: ['KOMPAS100', 'IDX80'] },
      'ESSA.JK': { name: 'Essa Indonesia Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'AMMN.JK': { name: 'Amman Mineral Internasional Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'PANI.JK': { name: 'Pantai Indah Kapuk Dua Tbk', sector: 'IDXPROPERT' ,sectorDesc: 'Properties & Real Estate', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'PTBA.JK': { name: 'Bukit Asam Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'KIJA.JK': { name: 'Kawasan Industri Jababeka Tbk', sector: 'IDXPROPERT' ,sectorDesc: 'Properties & Real Estate', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'JSMR.JK': { name: 'Jasa Marga (Persero) Tbk', sector: 'IDXINFRA', sectorDesc: 'Infrastructure', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'HMSP.JK': { name: 'H.M. Sampoerna Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'SMGR.JK': { name: 'Semen Indonesia Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'HRUM.JK': { name: 'Harum Energy Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'MAPI.JK': { name: 'Mitra Adiperkasa Tbk', sector: 'IDXCYCLIC', sectorDesc: 'Consumer Cyclicals', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'CPIN.JK': { name: 'Charoen Pokphand Indonesia Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'BRPT.JK': { name: 'Barito Pacific Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'ERAA.JK': { name: 'Erajaya Swasembada Tbk', sector: 'IDXCYCLIC', sectorDesc: 'Consumer Cyclicals', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'UNVR.JK': { name: 'Unilever Indonesia Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'BMRI.JK': { name: 'Bank Mandiri (Persero) Tbk', sector: 'IDXFINANCE' ,sectorDesc: 'Financials', indices: ['KOMPAS100', 'LQ45', 'IDX80'] },
      'KLBF.JK': { name: 'Kalbe Farma Tbk', sector: 'IDXHEALTH', sectorDesc: 'Healthcare', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'PSAB.JK': { name: 'J Resources Asia Pasifik Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'CMRY.JK': { name: 'Cisarua Mountain Dairy Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'MIKA.JK': { name: 'Mitra Keluarga Karyasehat Tbk', sector: 'IDXHEALTH', sectorDesc: 'Healthcare', indices: ['KOMPAS100', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'MEDC.JK': { name: 'Medco Energi Internasional Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'FILM.JK': { name: 'MD Pictures Tbk', sector: 'IDXCYCLIC', sectorDesc: 'Consumer Cyclicals', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'GOTO.JK': { name: 'GoTo Gojek Tokopedia Tbk', sector: 'IDXTECHNO', sectorDesc: 'Technology', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'BRIS.JK': { name: 'Bank Syariah Indonesia Tbk', sector: 'IDXFINANCE' ,sectorDesc: 'Financials', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'SMRA.JK': { name: 'Summarecon Agung Tbk', sector: 'IDXPROPERT' ,sectorDesc: 'Properties & Real Estate', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'SSIA.JK': { name: 'Surya Semesta Internusa Tbk', sector: 'IDXPROPERT' ,sectorDesc: 'Properties & Real Estate', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'DEWA.JK': { name: 'Dharma Henwa Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'JPFA.JK': { name: 'Japfa Comfeed Indonesia Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'BUKA.JK': { name: 'Bukalapak.com Tbk', sector: 'IDXTECHNO', sectorDesc: 'Technology', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'BTPS.JK': { name: 'BTPN Syariah Tbk', sector: 'IDXFINANCE' ,sectorDesc: 'Financials', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'MBMA.JK': { name: 'Merdeka Battery Materials Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'PTRO.JK': { name: 'Petrosea Tbk', sector: 'IDXINDUST' ,sectorDesc: 'Industrials', indices: ['KOMPAS100', 'LQ45', 'JII70', 'IDX80', 'ISSI'] },
      'HEAL.JK': { name: 'Medikaloka Hermina Tbk', sector: 'IDXHEALTH', sectorDesc: 'Healthcare', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'CBDK.JK': { name: 'Cideng Makmur Jaya Tbk', sector: 'IDXINDUST' ,sectorDesc: 'Industrials', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'BUMI.JK': { name: 'Bumi Resources Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'BBRI.JK': { name: 'Bank Rakyat Indonesia Tbk', sector: 'IDXFINANCE' ,sectorDesc: 'Financials', indices: ['KOMPAS100', 'LQ45', 'IDX80'] },
      'ICBP.JK': { name: 'Indofood CBP Sukses Makmur Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'MDKA.JK': { name: 'Merdeka Copper Gold Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'CUAN.JK': { name: 'Petrindo Jaya Kreasi Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'BBCA.JK': { name: 'Bank Central Asia Tbk', sector: 'IDXFINANCE' ,sectorDesc: 'Financials', indices: ['KOMPAS100', 'LQ45', 'IDX80'] },
      'EXCL.JK': { name: 'XL Axiata Tbk', sector: 'IDXINFRA', sectorDesc: 'Infrastructure', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'IDX80', 'ISSI'] },
      'ENRG.JK': { name: 'Energi Mega Persada Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'MYOR.JK': { name: 'Mayora Indah Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'EMTK.JK': { name: 'Elang Mahkota Teknologi Tbk', sector: 'IDXTECHNO', sectorDesc: 'Technology', indices: ['KOMPAS100', 'JII70', 'IDX80', 'ISSI'] },
      'BBNI.JK': { name: 'Bank Negara Indonesia Tbk', sector: 'IDXFINANCE' ,sectorDesc: 'Financials', indices: ['KOMPAS100', 'LQ45', 'IDX80'] },
      'BULL.JK': { name: 'Buana Lintas Lautan Tbk', sector: 'IDXTRANS', sectorDesc: 'Transportation & Logistics', indices: ['KOMPAS100', 'IDX80', 'ISSI'] },
      'KPIG.JK': { name: 'MNC Land Tbk', sector: 'IDXPROPERT' ,sectorDesc: 'Properties & Real Estate', indices: ['KOMPAS100', 'JII70', 'ISSI'] },
      'TPIA.JK': { name: 'Chandra Asri Pacific Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'JII70', 'ISSI'] },
      'BKSL.JK': { name: 'Sentul City Tbk', sector: 'IDXPROPERT' ,sectorDesc: 'Properties & Real Estate', indices: ['KOMPAS100', 'ISSI'] },
      'MAPA.JK': { name: 'Map Aktif Adiperkasa Tbk', sector: 'IDXCYCLIC', sectorDesc: 'Consumer Cyclicals', indices: ['KOMPAS100', 'JII70', 'ISSI'] },
      'IMPC.JK': { name: 'Impack Pratama Industri Tbk', sector: 'IDXPROPERT' ,sectorDesc: 'Properties & Real Estate', indices: ['KOMPAS100', 'JII70', 'ISSI'] },
      'BUVA.JK': { name: 'Bukit Uluwatu Villa Tbk', sector: 'IDXCYCLIC', sectorDesc: 'Consumer Cyclicals', indices: ['KOMPAS100', 'JII70', 'ISSI'] },
      'AMRT.JK': { name: 'Sumber Alfaria Trijaya Tbk', sector: 'IDXNONCYC', sectorDesc: 'Consumer Non-Cyclicals', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'ISSI'] },
      'ASII.JK': { name: 'Astra International Tbk', sector: 'IDXINDUST' ,sectorDesc: 'Industrials', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'ISSI'] },
      'RATU.JK': { name: 'Ratu Prabu Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'ISSI'] },
      'NCKL.JK': { name: 'Trimegah Bangun Persada Tbk', sector: 'IDXBASIC', sectorDesc: 'Basic Materials', indices: ['KOMPAS100', 'LQ45', 'ISSI'] },
      'SCMA.JK': { name: 'Surya Citra Media Tbk', sector: 'IDXCYCLIC', sectorDesc: 'Consumer Cyclicals', indices: ['KOMPAS100', 'JII70', 'ISSI'] },
      'SGER.JK': { name: 'Sumber Global Energy Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'JII70', 'ISSI'] },
      'TLKM.JK': { name: 'Telkom Indonesia Tbk', sector: 'IDXINFRA', sectorDesc: 'Infrastructure', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'ISSI'] },
      'TCPI.JK': { name: 'Transcoal Pacific Tbk', sector: 'IDXTRANS', sectorDesc: 'Transportation & Logistics', indices: ['KOMPAS100', 'ISSI'] },
      'RAJA.JK': { name: 'Rukun Raharja Tbk', sector: 'IDXENERGY', sectorDesc: 'Energy', indices: ['KOMPAS100', 'JII70', 'ISSI'] },
      'MTEL.JK': { name: 'Dayamitra Telekomunikasi Tbk', sector: 'IDXINFRA', sectorDesc: 'Infrastructure', indices: ['KOMPAS100', 'JII70', 'ISSI'] },
      'ISAT.JK': { name: 'Indosat Ooredoo Hutchison Tbk', sector: 'IDXINFRA', sectorDesc: 'Infrastructure', indices: ['KOMPAS100', 'JII70', 'ISSI'] },
      'BBYB.JK': { name: 'Bank Neo Commerce Tbk', sector: 'IDXFINANCE' ,sectorDesc: 'Financials', indices: ['KOMPAS100'] },
      'BREN.JK': { name: 'Barito Renewables Energy Tbk', sector: 'IDXINFRA', sectorDesc: 'Infrastructure', indices: ['KOMPAS100', 'LQ45', 'JII', 'JII70', 'ISSI'] },
      'ARTO.JK': { name: 'Bank Jago Tbk', sector: 'IDXFINANCE' ,sectorDesc: 'Financials', indices: ['KOMPAS100'] }
    };      