import { TICKERS, STOCK_DETAILS } from '../config/constants.js';                                                                                                                                               
 import YahooFinance from 'yahoo-finance2';                                                                                                                                                                     
    const yahooFinance = new YahooFinance({ suppressNotices: ['yahooSurvey'] });

class StockService {                                                                                                                                                                                           
  constructor() {                                                                                                                                                                                              
    this.cache = {                                                                                                                                                                                             
      data: [],                                                                                                                                                                                                
      lastUpdated: 0,                                                                                                                                                                                          
      ihsg: { price: 7230.45, change: 32.40, pct: 0.45 }                                                                                                                                                       
    };                                                                                                                                                                                                         
    this.CACHE_DURATION = 5 * 60 * 1000; // 5 Minutes                                                                                                                                                          
  }                                                                                                                                                                                                            
                                                                                                                                                                                                                
  // Renamed to getStocksData                                                                                                                                                                                  
  async getStocksData() {                                                                                                                                                                                      
    const now = Date.now();                                                                                                                                                                                    
    if (this.cache.data.length > 0 && (now - this.cache.lastUpdated < this.CACHE_DURATION)) {                                                                                                                  
      return { stocks: this.cache.data, ihsg: this.cache.ihsg };                                                                                                                                               
    }                                                                                                                                                                                                          
                                                                                                                                                                                                                
    console.log("Fetching new quotes from Yahoo Finance...");                                                                                                                                                  
    try {                                                                                                                                                                                                      
      const chunkSize = 25;                                                                                                                                                                                    
      let quotes = [];                                                                                                                                                                                         
      for (let i = 0; i < TICKERS.length; i += chunkSize) {                                                                                                                                                    
        const chunk = TICKERS.slice(i, i + chunkSize);                                                                                                                                                         
        const chunkQuotes = await yahooFinance.quote(chunk);                                                                                                                                                   
        quotes = quotes.concat(chunkQuotes);                                                                                                                                                                   
      }                                                                                                                                                                                                        
                                                                                                                                                                                                                
      let totalPrevCap = 0;                                                                                                                                                                                    
      let totalCurrentCap = 0;                                                                                                                                                                                 
                                                                                                                                                                                                                
      const formattedData = quotes.map(q => {                                                                                                                                                                  
        const ticker = q.symbol;                                                                                                                                                                               
        const details = STOCK_DETAILS[ticker] || { name: ticker.split('.')[0], sector: 'Others', indices: ['KOMPAS100'] };                                                                                     
        const currentPrice = q.regularMarketPrice || 0;                                                                                                                                                        
        const change = q.regularMarketChangePercent || 0;                                                                                                                                                      
        const prevPrice = q.regularMarketPreviousClose || Math.round(currentPrice / (1 + change/100));                                                                                                         
        const volume = q.regularMarketVolume || 0;                                                                                                                                                             
        const marketCap = q.marketCap || (currentPrice * (volume || 10000000));                                                                                                                                
                                                                                                                                                                                                                
        totalCurrentCap += marketCap;                                                                                                                                                                          
        totalPrevCap += (marketCap / (1 + change/100));                                                                                                                                                        
                                                                                                                                                                                                                
        // Maintain sparkline history array                                                                                                                                                                    
        const existingStock = this.cache.data.find(s => s.symbol === ticker.replace('.JK', ''));                                                                                                               
        let history = existingStock ? [...existingStock.history] : Array.from({length: 10}, () => currentPrice);                                                                                               
        if (history[history.length - 1] !== currentPrice) {                                                                                                                                                    
          history.push(currentPrice);                                                                                                                                                                          
          history.shift();                                                                                                                                                                                     
        }                                                                                                                                                                                                      
                                                                                                                                                                                                                
        return {                                                                                                                                                                                               
          symbol: ticker.replace('.JK', ''),                                                                                                                                                                   
          name: details.name,                                                                                                                                                                                  
          sector: details.sector,                                                                                                                                                                              
          indices: details.indices,                                                                                                                                                                            
          price: currentPrice,                                                                                                                                                                                 
          change: Number(change.toFixed(2)),                                                                                                                                                                   
          prevPrice,                                                                                                                                                                                           
          volume,                                                                                                                                                                                              
          marketCap,                                                                                                                                                                                           
          history                                                                                                                                                                                              
        };                                                                                                                                                                                                     
      });                                                                                                                                                                                                      
                                                                                                                                                                                                                
      if (totalPrevCap > 0) {                                                                                                                                                                                  
        const pct = ((totalCurrentCap - totalPrevCap) / totalPrevCap) * 100;                                                                                                                                   
        this.cache.ihsg.pct = Number(pct.toFixed(2));                                                                                                                                                          
        this.cache.ihsg.price = Number((7198.05 * (1 + pct/100)).toFixed(2));                                                                                                                                  
        this.cache.ihsg.change = Number((this.cache.ihsg.price - 7198.05).toFixed(2));                                                                                                                         
      }                                                                                                                                                                                                        
                                                                                                                                                                                                                
      this.cache.data = formattedData;                                                                                                                                                                         
      this.cache.lastUpdated = now;                                                                                                                                                                            
      return { stocks: this.cache.data, ihsg: this.cache.ihsg };                                                                                                                                               
    } catch (error) {                                                                                                                                                                                          
      console.error("Error in StockService.getStocksData:", error);                                                                                                                                            
      return { stocks: this.cache.data, ihsg: this.cache.ihsg }; // Fallback to cache                                                                                                                          
    }                                                                                                                                                                                                          
  }                                                                                                                                                                                                            
                                                                                                                                                                                                                
  // Get historical data for the selected stock                                                                                                                                                                
  async getStockHistory(symbol) {                                                                                                                                                                              
    const yahooSymbol = `${symbol.toUpperCase()}.JK`;                                                                                                                                                          
    try {                                                                                                                                                                                                      
      const today = new Date();                                                                                                                                                                                
      const thirtyDaysAgo = new Date();                                                                                                                                                                        
      thirtyDaysAgo.setDate(today.getDate() - 30);                                                                                                                                                             
                                                                                                                                                                                                                
      const period1 = thirtyDaysAgo.toISOString().split('T')[0];                                                                                                                                               
      const period2 = today.toISOString().split('T')[0];                                                                                                                                                       
                                                                                                                                                                                                                
      const result = await yahooFinance.historical(yahooSymbol, { period1, period2, interval: '1d' });                                                                                                         
      return result.map(item => ({                                                                                                                                                                             
        date: item.date,                                                                                                                                                                                       
        close: item.close,                                                                                                                                                                                     
        volume: item.volume                                                                                                                                                                                    
      }));                                                                                                                                                                                                     
    } catch (error) {                                                                                                                                                                                          
      console.warn(`Failed to fetch history for ${yahooSymbol}, using mock fallback:`, error.message);                                                                                                         
      const mockPrices = []; // 👈 Initialized correctly                                                                                                                                                       
      let current = 2500;                                                                                                                                                                                      
      for (let i = 0; i < 30; i++) {                                                                                                                                                                           
        mockPrices.push({                                                                                                                                                                                      
          date: new Date(Date.now() - (30 - i) * 24 * 60 * 60 * 1000).toISOString().split('T')[0],                                                                                                             
          close: current,                                                                                                                                                                                      
          volume: Math.round(Math.random() * 500000)                                                                                                                                                           
        });                                                                                                                                                                                                    
        current = Math.max(10, Math.round(current + (Math.random() - 0.5) * 80));                                                                                                                              
      }                                                                                                                                                                                                        
      return mockPrices;                                                                                                                                                                                       
    }                                                                                                                                                                                                          
  }                                                                                                                                                                                                            
}                                                                                                                                                                                                              
                                                                                                                                                                                                                
export const stockService = new StockService();