import { TICKERS, STOCK_DETAILS } from '../config/constants.js';                                                                                                                                             
import YahooFinance from 'yahoo-finance2';                                                                                                                                                                   
                                                                                                                                                                                                              
const yahooFinance = new YahooFinance({ suppressNotices: ['yahooSurvey'] });                                                                                                                                 
                                                                                                                                                                                                              
class StockService {                                                                                                                                                                                         
  constructor() {                                                                                                                                                                                            
    this.cache = {                                                                                                                                                                                           
      data: [],                                                                                                                                                                                              
      lastUpdated: 0,                                                                                                                                                                                        
      ihsg: { price: 7230.45, change: 32.40, pct: 0.45 }                                                                                                                                                     
    };                                                                                                                                                                                                       
    this.CACHE_DURATION = 5 * 60 * 1000; // 5 Minutes cache for live data                                                                                                                                    
  }                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                 
  async getStocksData(targetDate = null) {                                                                                                                                                                   
    const todayStr = new Date().toISOString().split('T')[0];                                                                                                                                                 
                                                                                                                                                                                                              
    // Case 1: Today's live quotes (or default when no targetDate is supplied)                                                                                                                               
    if (!targetDate || targetDate === todayStr) {                                                                                                                                                            
      const now = Date.now();                                                                                                                                                                                
      if (this.cache.data.length > 0 && (now - this.cache.lastUpdated < this.CACHE_DURATION)) {                                                                                                              
        return { stocks: this.cache.data, ihsg: this.cache.ihsg };                                                                                                                                           
      }                                                                                                                                                                                                      
                                                                                                                                                                                                              
      console.log("Fetching live quotes from Yahoo Finance...");                                                                                                                                             
      try {                                                                                                                                                                                                  
        // 1. Fetch IHSG (^JKSE) index quote                                                                                                                                                                 
        try {                                                                                                                                                                                                
          const ihsgQuote = await yahooFinance.quote('^JKSE');                                                                                                                                               
          if (ihsgQuote && ihsgQuote.regularMarketPrice) {                                                                                                                                                   
            const price = ihsgQuote.regularMarketPrice || 0;                                                                                                                                                 
            const change = ihsgQuote.regularMarketChange || 0;                                                                                                                                               
            const pct = ihsgQuote.regularMarketChangePercent || 0;                                                                                                                                           
            this.cache.ihsg = {                                                                                                                                                                              
              price: Number(price.toFixed(2)),                                                                                                                                                               
              change: Number(change.toFixed(2)),                                                                                                                                                             
              pct: Number(pct.toFixed(2))                                                                                                                                                                    
            };                                                                                                                                                                                               
          }                                                                                                                                                                                                  
        } catch (ihsgErr) {                                                                                                                                                                                  
          console.warn("Could not fetch IHSG quote from Yahoo Finance:", ihsgErr.message);                                                                                                                   
        }                                                                                                                                                                                                    
                                                                                                                                                                                                              
        // 2. Fetch stock quotes in chunks of 25                                                                                                                                                             
        const chunkSize = 25;                                                                                                                                                                                
        let quotes = [];                                                                                                                                                                                     
        for (let i = 0; i < TICKERS.length; i += chunkSize) {                                                                                                                                                
          const chunk = TICKERS.slice(i, i + chunkSize);                                                                                                                                                     
          const chunkQuotes = await yahooFinance.quote(chunk);                                                                                                                                               
          quotes = quotes.concat(chunkQuotes);                                                                                                                                                               
        }                                                                                                                                                                                                    
                                                                                                                                                                                                              
        const formattedData = quotes.map(q => {                                                                                                                                                              
          const ticker = q.symbol;                                                                                                                                                                           
          const details = STOCK_DETAILS[ticker] || { name: ticker.split('.')[0], sector: 'Others', indices: ['KOMPAS100'] };                                                                                 
          const currentPrice = q.regularMarketPrice || 0;                                                                                                                                                    
          const change = q.regularMarketChangePercent || 0;                                                                                                                                                  
          const prevPrice = q.regularMarketPreviousClose || Math.round(currentPrice / (1 + change / 100));                                                                                                   
          const volume = q.regularMarketVolume || 0;                                                                                                                                                         
          const marketCap = q.marketCap || (currentPrice * (volume || 10000000));                                                                                                                            
                                                                                                                                                                                                              
          // Maintain sparkline history array                                                                                                                                                                
          const existingStock = this.cache.data.find(s => s.symbol === ticker.replace('.JK', ''));                                                                                                           
          let history = existingStock ? [...existingStock.history] : Array.from({ length: 10 }, () => currentPrice);                                                                                         
          if (history[history.length - 1] !== currentPrice) {                                                                                                                                                
            history.push(currentPrice);                                                                                                                                                                      
            history.shift();                                                                                                                                                                                 
          }                                                                                                                                                                                                  
                                                                                                                                                                                                              
          return {                                                                                                                                                                                           
            symbol: ticker.replace('.JK', ''),                                                                                                                                                               
            name: details.name,                                                                                                                                                                              
            sector: details.sector,                                                                                                                                                                          
            indices: details.indices,                                                                                                                                                                        
            price: currentPrice,                                                                                                                                                                             
            change: Number(change.toFixed(2)),                                                                                                                                                               
            prevPrice,                                                                                                                                                                                       
            volume,                                                                                                                                                                                          
            marketCap,                                                                                                                                                                                       
            history                                                                                                                                                                                          
          };                                                                                                                                                                                                 
        });                                                                                                                                                                                                  
                                                                                                                                                                                                              
        this.cache.data = formattedData;                                                                                                                                                                     
        this.cache.lastUpdated = now;                                                                                                                                                                        
        return { stocks: this.cache.data, ihsg: this.cache.ihsg };                                                                                                                                           
      } catch (error) {                                                                                                                                                                                      
        console.error("Error in StockService.getStocksData:", error);                                                                                                                                        
        return { stocks: this.cache.data, ihsg: this.cache.ihsg };                                                                                                                                           
      }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                              
    // Case 2: Historical Date Query (targetDate = YYYY-MM-DD)                                                                                                                                               
    //console.log(`Fetching historical stock data for target date: ${targetDate}`);                                                                                                                            
    try {                                                                                                                                                                                                    
      const selected = new Date(targetDate);                                                                                                                                                                 
      const prevDate = new Date(selected);                                                                                                                                                                   
      prevDate.setDate(selected.getDate() - 7); // 7-day lookback window for weekends/market holidays                                                                                                        
                                                                                                                                                                                                              
      const period1 = prevDate.toISOString().split('T')[0];   
          
      const period2Date = new Date(selected);
      period2Date.setDate(selected.getDate() + 1);         
                                                                                                                                       
      const period2 = period2Date.toISOString().split('T')[0];                                                                                                                                                  
                                                                                                                                                                                                              
      // 1. Fetch historical IHSG data for targetDate                                                                                                                                                        
      let ihsgData = { ...this.cache.ihsg };                                                                                                                                                                 
      try {                                                                                                                                                                                                  
        const ihsgHistory = await yahooFinance.historical('^JKSE', { period1, period2, interval: '1d' });                                                                                                    
        if (ihsgHistory && ihsgHistory.length >= 1) {                                                                                                                                                        
          const latest = ihsgHistory[ihsgHistory.length - 1];                                                                                                                                                
          const previous = ihsgHistory.length >= 2 ? ihsgHistory[ihsgHistory.length - 2] : latest;                                                                                                           
          const change = latest.close - previous.close;                                                                                                                                                      
          const pct = previous.close > 0 ? (change / previous.close) * 100 : 0;                                                                                                                              
          ihsgData = {                                                                                                                                                                                       
            price: Number(latest.close.toFixed(2)),                                                                                                                                                          
            change: Number(change.toFixed(2)),                                                                                                                                                               
            pct: Number(pct.toFixed(2))                                                                                                                                                                      
          };                                                                                                                                                                                                 
        }                                                                                                                                                                                                    
      } catch (err) {                                                                                                                                                                                        
        console.warn(`Could not fetch historical IHSG for ${targetDate}:`, err.message);                                                                                                                     
      }                                                                                                                                                                                                      
                                                                                                                                                                                                              
      // 2. Fetch historical quotes for all tickers in parallel chunks                                                                                                                                       
      const chunkSize = 15;                                                                                                                                                                                  
      const historicalStocks = [];                                                                                                                                                                           
                                                                                                                                                                                                              
      for (let i = 0; i < TICKERS.length; i += chunkSize) {                                                                                                                                                  
        const chunk = TICKERS.slice(i, i + chunkSize);                                                                                                                                                       
        const chunkPromises = chunk.map(async (ticker) => {                                                                                                                                                  
          const details = STOCK_DETAILS[ticker] || { name: ticker.split('.')[0], sector: 'Others', indices: ['KOMPAS100'] };                                                                                 
          const symbol = ticker.replace('.JK', '');                                                                                                                                                          
                                                                                                                                                                                                              
          try {                                                                                                                                                                                              
            const hist = await yahooFinance.historical(ticker, { period1, period2, interval: '1d' });                                                                                                        
            if (hist && hist.length > 0) {                                                                                                                                                                   
              const latest = hist[hist.length - 1];                                                                                                                                                          
              const previous = hist.length >= 2 ? hist[hist.length - 2] : latest;                                                                                                                            
              const price = latest.close || 0;                                                                                                                                                               
              const prevPrice = previous.close || price;                                                                                                                                                     
              const change = prevPrice > 0 ? ((price - prevPrice) / prevPrice) * 100 : 0;                                                                                                                    
              const volume = latest.volume || 0;                                                                                                                                                             
              const historyPoints = hist.slice(-10).map(h => h.close);                                                                                                                                       
                                                                                                                                                                                                              
              return {                                                                                                                                                                                       
                symbol,                                                                                                                                                                                      
                name: details.name,                                                                                                                                                                          
                sector: details.sector,                                                                                                                                                                      
                indices: details.indices,                                                                                                                                                                    
                price: Number(price.toFixed(2)),                                                                                                                                                             
                change: Number(change.toFixed(2)),                                                                                                                                                           
                prevPrice: Number(prevPrice.toFixed(2)),                                                                                                                                                     
                volume,                                                                                                                                                                                      
                marketCap: price * (volume || 10000000),                                                                                                                                                     
                history: historyPoints.length >= 10 ? historyPoints : Array.from({ length: 10 }, () => price)                                                                                                
              };                                                                                                                                                                                             
            }                                                                                                                                                                                                
          } catch (err) {                                                                                                                                                                                    
            // Fallback if no history was returned for ticker on that day                                                                                                                                    
          }                                                                                                                                                                                                  
                                                                                                                                                                                                              
          // Fallback to cache item if available                                                                                                                                                             
          const cached = this.cache.data.find(s => s.symbol === symbol);                                                                                                                                     
          return cached || {                                                                                                                                                                                 
            symbol,                                                                                                                                                                                          
            name: details.name,                                                                                                                                                                              
            sector: details.sector,                                                                                                                                                                          
            indices: details.indices,                                                                                                                                                                        
            price: 1000,                                                                                                                                                                                     
            change: 0,                                                                                                                                                                                       
            prevPrice: 1000,                                                                                                                                                                                 
            volume: 50000,                                                                                                                                                                                   
            marketCap: 5000000000,                                                                                                                                                                           
            history: Array(10).fill(1000)                                                                                                                                                                    
          };                                                                                                                                                                                                 
        });                                                                                                                                                                                                  
                                                                                                                                                                                                              
        const chunkResults = await Promise.all(chunkPromises);                                                                                                                                               
        historicalStocks.push(...chunkResults);                                                                                                                                                              
      }                                                                                                                                                                                                      
                                                                                                                                                                                                              
      return { stocks: historicalStocks, ihsg: ihsgData };                                                                                                                                                   
    } catch (error) {                                                                                                                                                                                        
      console.error(`Failed to fetch historical date quotes for ${targetDate}:`, error);                                                                                                                     
      return { stocks: this.cache.data, ihsg: this.cache.ihsg };                                                                                                                                             
    }                                                                                                                                                                                                        
  }                                                                                                                                                                                                          
                                                                                                                                                                                                              
  // Get historical chart data for single selected stock                                                                                                                                                     
  async getStockHistory(symbol) {                                                                                                                                                                            
    const yahooSymbol = `${symbol.toUpperCase()}.JK`;                                                                                                                                                        
    try {                                                                                                                                                                                                    
      const today = new Date();                                                                                                                                                                              
      const thirtyDaysAgo = new Date();                                                                                                                                                                      
      thirtyDaysAgo.setDate(today.getDate() - 30);                                                                                                                                                           
                                                                                                                                                                                                              
      const period1 = thirtyDaysAgo.toISOString().split('T')[0];                                                                                                                                             
      const period2 = today.toISOString().split('T')[0];                                                                                                                                                     
                                                                                                                                                                                                              
      const result = await yahooFinance.historical(yahooSymbol, { period1, period2, interval: '1d' });                                                                                                       
      return result.map(item => ({                                                                                                                                                                           
        date: item.date,                                                                                                                                                                                     
        close: item.close,                                                                                                                                                                                   
        volume: item.volume                                                                                                                                                                                  
      }));                                                                                                                                                                                                   
    } catch (error) {                                                                                                                                                                                        
      console.warn(`Failed to fetch history for ${yahooSymbol}, using mock fallback:`, error.message);                                                                                                       
      const mockPrices = [];                                                                                                                                                                                 
      let current = 2500;                                                                                                                                                                                    
      for (let i = 0; i < 30; i++) {                                                                                                                                                                         
        mockPrices.push({                                                                                                                                                                                    
          date: new Date(Date.now() - (30 - i) * 24 * 60 * 60 * 1000).toISOString().split('T')[0],                                                                                                           
          close: current,                                                                                                                                                                                    
          volume: Math.round(Math.random() * 500000)                                                                                                                                                         
        });                                                                                                                                                                                                  
        current = Math.max(10, Math.round(current + (Math.random() - 0.5) * 80));                                                                                                                            
      }                                                                                                                                                                                                      
      return mockPrices;                                                                                                                                                                                     
    }                                                                                                                                                                                                        
  }                                                                                                                                                                                                          
}                                                                                                                                                                                                            
                                                                                                                                                                                                              
export const stockService = new StockService();  